sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
php:
- 5.6
- 7.1
before_deploy:
  - npm run build
  - npm run zip
  - export RELEASE_FILE=$(ls oleinpress-weblog.zip)
deploy:
  provider: releases
  api_key:
    secure: B1tNMxasQNgevpENvmL0XwkEMgA1mOKgMgE59Co6hemUgzuOsdcmWruB1bGNIM/uvuU6o0CLy6Mabd7FLuXMUHRvL/YSX+QEGEXNJyhQDLNFUjZXE5EzuDEkaionzX9RPo6gN7S0L5oKLykthwqdwOSUWSXULBTTULy2UAxSw9ccwS1vSlYQTNqcbu07RB7wj6qz4n+SJzVA36RAfckOHkQBenpUBKewBmghANVnEXyp9s+A/js8SKwzFL9W6nZp2aKE46Xk/CYu0fktnPfF85yqPaZu7YogRxVU81k7H8UvaPGJzlYaoTbcRIJIT4Et80ZrQd1LHn7RqH1xdQO1iy2Mu80vfiddJKziLDIIQPVn3Olek5utRIjkPvtnewXt0ooKuDCTMYKUVNDkcwn7xesoi6TQpQ7N2HT6LeQqopLnHlCeieG94WmRZ6O4In25r8jNCNjFIDISEi0QIbLUPGesRgqW9ae9fZhqzovof1AVd/jaJ8/5taxRDQ5z4zqhFmxplBG0BbKBpenuoEnsnXyaujdrOeBt1os8VIEbQDbV+SrfconxAqz6Am3b3lSCw16SNC7lfa5TGoxpDulBbuNZldDoDIpGBfzgKNE9bdVWRoQrsVM417af7I1aX4xrVSC+PHR9O2YZnwFIN0Y9GfNK9yvotxc2f+MjdD+RXZc=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    php: 7.1
    repo: Olein-jp/oleinpress-weblog